In [7]:
# basic libraries
import numpy as np
import xarray as xr
import pandas as pd
import matplotlib.pyplot as plt
from pandas.plotting import register_matplotlib_converters

# libraries for maps
import cartopy.crs as ccrs
import cartopy.feature as cfeature

# units libraries
import metpy.calc as mpcalc
from metpy.units import units

# time libraries
import matplotlib.dates as mdates

# Plots libraries
import matplotlib.colors as mcolors
import seaborn as sns
import matplotlib.colors as colors
from matplotlib.lines import Line2D
import os

# buoy analysis library
from scipy.spatial import cKDTree

Donwload buoy dataset

In [ ]:
import copernicusmarine

copernicusmarine.subset(
  dataset_id="cmems_obs-ins_med_phybgcwav_mynrt_na_irr",
  dataset_part="monthly",
  variables=["VAVH", "VGHS", "VHM0"],
  minimum_longitude=-6,
  maximum_longitude=37,
  minimum_latitude=30,
  maximum_latitude=46,
  start_datetime="2020-01-01T00:00:00",
  end_datetime="2021-01-01T00:00:00",
  minimum_depth=0,
  maximum_depth=0,
  output_filename="C://Users//kosta//OneDrive//Desktop//Διπλωματική//Data//byos"  # where to store the data
)

""" Some other dataset
copernicusmarine.subset(
  dataset_id="cmems_obs-wind_med_phy_my_l3-s1a-sar-desc-0.01deg_P1D-i",
  variables=["eastward_wind", "northward_wind", "rejection_flag", "measurement_time", "quality_level"],
  minimum_longitude=-5.604000091552734,
  maximum_longitude=36.80400085449219,
  minimum_latitude=30.125999450683594,
  maximum_latitude=46.00199890136719,
  start_datetime="2020-09-19T00:00:00",
  end_datetime="2020-09-20T00:00:00",
  output_filename="C://Users//kosta//OneDrive//Desktop//Διπλωματική//Data"  # where to store the data
)"""

INFO - 2025-11-27T10:12:18Z - Downloading Copernicus Marine data requires a Copernicus Marine username and password, sign up for free at: https://data.marine.copernicus.eu/register

Copernicus Marine username:Copernicus Marine password:

INFO - 2025-11-27T10:12:27Z - Selected dataset version: "202311"
INFO - 2025-11-27T10:12:27Z - Selected dataset part: "monthly"
Downloading files: 100%|██████████| 57/57 [00:11<00:00,  5.03it/s]

ResponseSubset(file_path=WindowsPath('C:/Users/kosta/OneDrive/Desktop/Διπλωματική/Data/byos.csv'), output_directory=WindowsPath('.'), filename='C:\\Users\\kosta\\OneDrive\\Desktop\\Διπλωματική\\Data\\byos.csv', file_size=None, data_transfer_size=None, variables=['VAVH', 'VGHS', 'VHM0'], coordinates_extent=[], status='000', message='The request was successful.', file_status='DOWNLOADED')

Dataset used for latitude, longitude definition

In [ ]:
ds_0 = xr.open_dataset("C://Users//kosta//OneDrive//Desktop//Διπλωματική//Results//Maps_diff//hs_mean_diff01.nc", engine="h5netcdf")
ds_0

<xarray.Dataset> Size: 16MB
Dimensions:    (time: 1, bnds: 2, latitude: 787, longitude: 1651)
Coordinates:
    latitude   (latitude, longitude) float32 5MB ...
    longitude  (latitude, longitude) float32 5MB ...
  * time       (time) datetime64[ns] 8B 2020-01-16T11:30:00
Dimensions without coordinates: bnds
Data variables:
    time_bnds  (time, bnds) datetime64[ns] 16B ...
    diff       (time, latitude, longitude) float32 5MB ...
Attributes: (12/22)
    CDI:                              Climate Data Interface version 1.9.6 (h...
    Conventions:                      CF-1.6
    WAVEWATCH_III_version_number:     6.07
    WAVEWATCH_III_switches:           F90 NOGRB NC4 SHRD PR3 UQ FLX0 LN1 ST4 ...
    SIN4 namelist parameter BETAMAX:  1.55
    product_name:                     ww3.run_with_currents202001.nc
    ...                               ...
    start_date:                       2020-01-01 00:00:00
    stop_date:                        2020-01-31 23:00:00
    CDO:                              Climate Data Operators version 1.9.6 (h...
    history:                          Thu Oct  9 13:26:05 2025: ncks -A lan_l...
    history_of_appended_files:        Thu Oct  9 13:26:05 2025: Appended file...
    NCO:                              "4.5.2"

Buoys dataset

In [2]:
import pandas as pd
csv_file = "C://Users//kosta//OneDrive//Desktop//Διπλωματική//Data//byos.csv"

# 1. Read the CSV into a pandas DataFrame
df_altim = pd.read_csv(csv_file)
print("Pandas DataFrame:")
print(df_altim)

Pandas DataFrame:
       variable           platform_id platform_type                  time  \
0          VAVH               1801573            SD  2020-03-05T22:30:00Z
1          VAVH               1801573            SD  2020-03-05T23:00:00Z
2          VAVH               1801573            SD  2020-03-05T23:30:00Z
3          VAVH               1801573            SD  2020-03-06T00:00:00Z
4          VAVH               1801573            SD  2020-03-06T00:30:00Z
...         ...                   ...           ...                   ...
546185     VHM0  Tarragona-coast-buoy            MO  2020-12-31T20:00:00Z
546186     VHM0  Tarragona-coast-buoy            MO  2020-12-31T21:00:00Z
546187     VHM0  Tarragona-coast-buoy            MO  2020-12-31T22:00:00Z
546188     VHM0  Tarragona-coast-buoy            MO  2020-12-31T23:00:00Z
546189     VHM0  Tarragona-coast-buoy            MO  2021-01-01T00:00:00Z

        longitude  latitude  depth  pressure  is_depth_from_producer  value  \
0        -5.99110  36.01513   -0.0       NaN                       1  1.230
1        -5.94570  36.01550   -0.0       NaN                       1  1.202
2        -5.90193  36.00592   -0.0       NaN                       1  1.252
3        -5.86360  36.01642   -0.0       NaN                       1  1.395
4        -5.88002  36.00364   -0.0       NaN                       1  1.341
...           ...       ...    ...       ...                     ...    ...
546185    1.19000  41.07000   -0.0       NaN                       1  0.380
546186    1.19000  41.07000   -0.0       NaN                       1  0.360
546187    1.19000  41.07000   -0.0       NaN                       1  0.380
546188    1.19000  41.07000   -0.0       NaN                       1  0.460
546189    1.19000  41.07000   -0.0       NaN                       1  0.510

        value_qc         institution  \
0              1           Saildrone
1              1           Saildrone
2              1           Saildrone
3              1           Saildrone
4              1           Saildrone
...          ...                 ...
546185         1  Puertos del Estado
546186         1  Puertos del Estado
546187         1  Puertos del Estado
546188         1  Puertos del Estado
546189         1  Puertos del Estado

                                                      doi  \
0       https://doi.org/10.13155/59938 https://doi.org...
1       https://doi.org/10.13155/59938 https://doi.org...
2       https://doi.org/10.13155/59938 https://doi.org...
3       https://doi.org/10.13155/59938 https://doi.org...
4       https://doi.org/10.13155/59938 https://doi.org...
...                                                   ...
546185  https://doi.org/10.13155/59938 https://doi.org...
546186  https://doi.org/10.13155/59938 https://doi.org...
546187  https://doi.org/10.13155/59938 https://doi.org...
546188  https://doi.org/10.13155/59938 https://doi.org...
546189  https://doi.org/10.13155/59938 https://doi.org...

                               product_doi
0       https://doi.org/10.48670/moi-00044
1       https://doi.org/10.48670/moi-00044
2       https://doi.org/10.48670/moi-00044
3       https://doi.org/10.48670/moi-00044
4       https://doi.org/10.48670/moi-00044
...                                    ...
546185  https://doi.org/10.48670/moi-00044
546186  https://doi.org/10.48670/moi-00044
546187  https://doi.org/10.48670/moi-00044
546188  https://doi.org/10.48670/moi-00044
546189  https://doi.org/10.48670/moi-00044

[546190 rows x 14 columns]

C:\Users\kosta\AppData\Local\Temp\ipykernel_6608\2298872534.py:5: DtypeWarning: Columns (1) have mixed types. Specify dtype option on import or set low_memory=False.
  df_altim = pd.read_csv(csv_file)

Drop nan values of a parameter

In [4]:
df_altim = df_altim.dropna(subset=['value'])
df_altim

,variable,platform_id,platform_type,time,longitude,latitude,depth,pressure,is_depth_from_producer,value,value_qc,institution,doi,product_doi
0,VAVH,1801573,SD,2020-03-05T22:30:00Z,-5.99110,36.01513,-0.0,NaN,1,1.230,1,Saildrone,https://doi.org/10.13155/59938 https://doi.org...,https://doi.org/10.48670/moi-00044
1,VAVH,1801573,SD,2020-03-05T23:00:00Z,-5.94570,36.01550,-0.0,NaN,1,1.202,1,Saildrone,https://doi.org/10.13155/59938 https://doi.org...,https://doi.org/10.48670/moi-00044
2,VAVH,1801573,SD,2020-03-05T23:30:00Z,-5.90193,36.00592,-0.0,NaN,1,1.252,1,Saildrone,https://doi.org/10.13155/59938 https://doi.org...,https://doi.org/10.48670/moi-00044
3,VAVH,1801573,SD,2020-03-06T00:00:00Z,-5.86360,36.01642,-0.0,NaN,1,1.395,1,Saildrone,https://doi.org/10.13155/59938 https://doi.org...,https://doi.org/10.48670/moi-00044
4,VAVH,1801573,SD,2020-03-06T00:30:00Z,-5.88002,36.00364,-0.0,NaN,1,1.341,1,Saildrone,https://doi.org/10.13155/59938 https://doi.org...,https://doi.org/10.48670/moi-00044
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
546185,VHM0,Tarragona-coast-buoy,MO,2020-12-31T20:00:00Z,1.19000,41.07000,-0.0,NaN,1,0.380,1,Puertos del Estado,https://doi.org/10.13155/59938 https://doi.org...,https://doi.org/10.48670/moi-00044
546186,VHM0,Tarragona-coast-buoy,MO,2020-12-31T21:00:00Z,1.19000,41.07000,-0.0,NaN,1,0.360,1,Puertos del Estado,https://doi.org/10.13155/59938 https://doi.org...,https://doi.org/10.48670/moi-00044
546187,VHM0,Tarragona-coast-buoy,MO,2020-12-31T22:00:00Z,1.19000,41.07000,-0.0,NaN,1,0.380,1,Puertos del Estado,https://doi.org/10.13155/59938 https://doi.org...,https://doi.org/10.48670/moi-00044
546188,VHM0,Tarragona-coast-buoy,MO,2020-12-31T23:00:00Z,1.19000,41.07000,-0.0,NaN,1,0.460,1,Puertos del Estado,https://doi.org/10.13155/59938 https://doi.org...,https://doi.org/10.48670/moi-00044
546189,VHM0,Tarragona-coast-buoy,MO,2021-01-01T00:00:00Z,1.19000,41.07000,-0.0,NaN,1,0.510,1,Puertos del Estado,https://doi.org/10.13155/59938 https://doi.org...,https://doi.org/10.48670/moi-00044

Check platform's id

In [ ]:
# using drop_duplicates() to drop duplicate values, and reset_index() to reset the index of the dataset, in order to know how many buoys we have.
# Finally, we used drop=True, inside reset_index() to drop a new column, named "index", that would be added via reset_index() fuction.
unique_platform = df_altim[['platform_id']].drop_duplicates().reset_index(drop=True)
unique_platform

             platform_id
0                1801573
1                5801955
2                6100002
3                6100021
4                6100022
5                6100188
6                6100190
7                6100191
8                6100289
9                6100294
10               6100295
11               6100295
12               6100431
13               6101404
14             ADN-DWRG1
15             ADN-DWRG2
16             ADN-DWRG3
17  Barcelona-coast-buoy
18              CAPOMELE
19      Ceuta-coast-buoy
20               Kariani
21     Malaga-coast-buoy
22    Melilla-coast-buoy
23                 OBSEA
24     Tarifa-coast-buoy
25  Tarragona-coast-buoy
26               6100290
27               6100021
28               6100022
29               6100196
30               6100197
31               6100198
32               6100280
33               6100281
34               6100284
35               6100417
36               6100430
37               6100431
38               6101404
39               6101628
40               6101629
41                 61277
42                 61277
43                 61499
44                 68422
45                 ATHOS
46             HERAKLION
47                 MYKON

Check data by each platform

In [43]:
df_HERAKLION = df_altim[df_altim['platform_id'] == 'HERAKLION']
#df_HERAKLION = df_HERAKLION[['value']] # if you want to check only the SWH measured by the buoy in HERAKLION station
df_HERAKLION

,variable,platform_id,platform_type,time,longitude,latitude,depth,pressure,is_depth_from_producer,value,value_qc,institution,doi,product_doi
515810,VHM0,HERAKLION,MO,2020-01-06T18:00:00Z,25.0792,35.4342,-0.0,NaN,1,4.570,1,Hellenic Centre for Marine Research - Institut...,https://doi.org/10.48670/moi-00044 https://doi...,https://doi.org/10.48670/moi-00044
515811,VHM0,HERAKLION,MO,2020-01-06T21:00:00Z,25.0792,35.4342,-0.0,NaN,1,4.453,1,Hellenic Centre for Marine Research - Institut...,https://doi.org/10.48670/moi-00044 https://doi...,https://doi.org/10.48670/moi-00044
515812,VHM0,HERAKLION,MO,2020-01-07T00:00:00Z,25.0792,35.4342,-0.0,NaN,1,5.273,1,Hellenic Centre for Marine Research - Institut...,https://doi.org/10.48670/moi-00044 https://doi...,https://doi.org/10.48670/moi-00044
515813,VHM0,HERAKLION,MO,2020-01-07T06:00:00Z,25.0792,35.4342,-0.0,NaN,1,5.156,1,Hellenic Centre for Marine Research - Institut...,https://doi.org/10.48670/moi-00044 https://doi...,https://doi.org/10.48670/moi-00044
515814,VHM0,HERAKLION,MO,2020-01-07T09:00:00Z,25.0792,35.4342,-0.0,NaN,1,4.687,1,Hellenic Centre for Marine Research - Institut...,https://doi.org/10.48670/moi-00044 https://doi...,https://doi.org/10.48670/moi-00044
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
517605,VHM0,HERAKLION,MO,2020-12-30T18:00:00Z,25.0792,35.4342,-0.0,NaN,1,0.505,1,Hellenic Centre for Marine Research - Institut...,https://doi.org/10.48670/moi-00044 https://doi...,https://doi.org/10.48670/moi-00044
517606,VHM0,HERAKLION,MO,2020-12-30T21:00:00Z,25.0792,35.4342,-0.0,NaN,1,0.374,1,Hellenic Centre for Marine Research - Institut...,https://doi.org/10.48670/moi-00044 https://doi...,https://doi.org/10.48670/moi-00044
517607,VHM0,HERAKLION,MO,2020-12-31T18:00:00Z,25.0792,35.4342,-0.0,NaN,1,0.000,1,Hellenic Centre for Marine Research - Institut...,https://doi.org/10.48670/moi-00044 https://doi...,https://doi.org/10.48670/moi-00044
517608,VHM0,HERAKLION,MO,2020-12-31T21:00:00Z,25.0792,35.4342,-0.0,NaN,1,0.346,1,Hellenic Centre for Marine Research - Institut...,https://doi.org/10.48670/moi-00044 https://doi...,https://doi.org/10.48670/moi-00044
517609,VHM0,HERAKLION,MO,2021-01-01T00:00:00Z,25.0792,35.4342,-0.0,NaN,1,0.383,1,Hellenic Centre for Marine Research - Institut...,https://doi.org/10.48670/moi-00044 https://doi...,https://doi.org/10.48670/moi-00044

Find the unique latitude/longitude of each measurement

In [8]:
unique_coords = df_altim[['longitude', 'latitude']].drop_duplicates()
unique_coords

        longitude  latitude
0        -5.99110  36.01513
1        -5.94570  36.01550
2        -5.90193  36.00592
3        -5.86360  36.01642
4        -5.88002  36.00364
...           ...       ...
459616    2.70040  39.49280
465294   21.60680  36.82880
497254   24.72940  39.97500
515810   25.07920  35.43420
519447   25.45970  37.51940

[11209 rows x 2 columns]

Find the range of lon/lat of measurements

In [9]:
lon_min, lon_max = df_altim['longitude'].min(), df_altim['longitude'].max()
lat_min, lat_max = df_altim['latitude'].min(), df_altim['latitude'].max()

print("Longitude range:", lon_min, lon_max)
print("Latitude range:", lat_min, lat_max)

Longitude range: -5.9911 25.4597
Latitude range: 35.327 45.6995

Counts the number of measurements in each lon/lat

In [10]:
lon_counts = df_altim['longitude'].value_counts()
lat_counts = df_altim['latitude'].value_counts()
lon_counts, lat_counts

(longitude
  3.77970    34792
  3.12450    34377
  5.23000    34356
  4.13330    32069
  3.16830    31945
             ...
 -4.22956        1
 -4.22845        1
 -4.22876        1
 -4.22914        1
 -5.86870        1
 Name: count, Length: 11066, dtype: int64,
 latitude
 43.37150    34792
 42.91620    34377
 43.20834    34356
 43.42500    32069
 42.48830    31945
             ...
 36.28476        1
 36.28465        1
 36.28501        1
 36.28559        1
 38.08967        1
 Name: count, Length: 10977, dtype: int64)

Check the unique dates of measurements

In [12]:
df_altim['time'] = pd.to_datetime(df_altim['time'])

# Extract only the date part (YYYY-MM-DD)
df_altim['date'] = df_altim['time'].dt.date

# Get unique dates
unique_dates = df_altim['date'].unique()
unique_dates

array([datetime.date(2020, 3, 5), datetime.date(2020, 3, 6),
       datetime.date(2020, 3, 7), datetime.date(2020, 3, 8),
       datetime.date(2020, 3, 9), datetime.date(2020, 3, 10),
       datetime.date(2020, 3, 11), datetime.date(2020, 3, 12),
       datetime.date(2020, 3, 13), datetime.date(2020, 3, 14),
       datetime.date(2020, 3, 15), datetime.date(2020, 3, 16),
       datetime.date(2020, 3, 17), datetime.date(2020, 3, 18),
       datetime.date(2020, 3, 19), datetime.date(2020, 3, 20),
       datetime.date(2020, 3, 21), datetime.date(2020, 3, 22),
       datetime.date(2020, 3, 23), datetime.date(2020, 3, 24),
       datetime.date(2020, 3, 25), datetime.date(2020, 3, 26),
       datetime.date(2020, 3, 27), datetime.date(2020, 3, 28),
       datetime.date(2020, 3, 29), datetime.date(2020, 3, 30),
       datetime.date(2020, 3, 31), datetime.date(2020, 4, 1),
       datetime.date(2020, 4, 2), datetime.date(2020, 4, 3),
       datetime.date(2020, 4, 4), datetime.date(2020, 4, 5),
       datetime.date(2020, 4, 6), datetime.date(2020, 4, 7),
       datetime.date(2020, 4, 8), datetime.date(2020, 4, 9),
       datetime.date(2020, 4, 10), datetime.date(2020, 4, 11),
       datetime.date(2020, 4, 12), datetime.date(2020, 4, 13),
       datetime.date(2020, 4, 14), datetime.date(2020, 4, 15),
       datetime.date(2020, 4, 16), datetime.date(2020, 4, 17),
       datetime.date(2020, 4, 18), datetime.date(2020, 4, 19),
       datetime.date(2020, 4, 20), datetime.date(2020, 4, 21),
       datetime.date(2020, 4, 22), datetime.date(2020, 4, 23),
       datetime.date(2020, 4, 24), datetime.date(2020, 4, 25),
       datetime.date(2020, 4, 26), datetime.date(2020, 4, 27),
       datetime.date(2020, 4, 28), datetime.date(2020, 4, 29),
       datetime.date(2020, 4, 30), datetime.date(2020, 5, 1),
       datetime.date(2020, 5, 2), datetime.date(2020, 5, 3),
       datetime.date(2020, 5, 4), datetime.date(2020, 5, 5),
       datetime.date(2020, 5, 6), datetime.date(2020, 5, 7),
       datetime.date(2020, 5, 8), datetime.date(2020, 5, 9),
       datetime.date(2020, 5, 10), datetime.date(2020, 5, 11),
       datetime.date(2020, 5, 12), datetime.date(2020, 5, 13),
       datetime.date(2020, 5, 14), datetime.date(2020, 5, 15),
       datetime.date(2020, 5, 16), datetime.date(2020, 5, 17),
       datetime.date(2020, 5, 18), datetime.date(2020, 5, 19),
       datetime.date(2020, 5, 20), datetime.date(2020, 5, 21),
       datetime.date(2020, 5, 22), datetime.date(2020, 5, 23),
       datetime.date(2020, 5, 24), datetime.date(2020, 5, 25),
       datetime.date(2020, 5, 26), datetime.date(2020, 5, 27),
       datetime.date(2020, 5, 28), datetime.date(2020, 5, 29),
       datetime.date(2020, 5, 30), datetime.date(2020, 6, 7),
       datetime.date(2020, 6, 8), datetime.date(2020, 6, 9),
       datetime.date(2020, 6, 10), datetime.date(2020, 6, 11),
       datetime.date(2020, 6, 12), datetime.date(2020, 6, 13),
       datetime.date(2020, 6, 14), datetime.date(2020, 6, 15),
       datetime.date(2020, 6, 16), datetime.date(2020, 6, 17),
       datetime.date(2020, 6, 18), datetime.date(2020, 6, 19),
       datetime.date(2020, 6, 20), datetime.date(2020, 6, 21),
       datetime.date(2020, 6, 22), datetime.date(2020, 6, 23),
       datetime.date(2020, 6, 24), datetime.date(2020, 6, 25),
       datetime.date(2020, 6, 26), datetime.date(2020, 6, 27),
       datetime.date(2020, 6, 28), datetime.date(2020, 6, 29),
       datetime.date(2020, 6, 30), datetime.date(2020, 7, 1),
       datetime.date(2020, 7, 2), datetime.date(2020, 7, 3),
       datetime.date(2020, 7, 4), datetime.date(2020, 7, 5),
       datetime.date(2020, 7, 6), datetime.date(2020, 7, 7),
       datetime.date(2020, 7, 8), datetime.date(2020, 7, 9),
       datetime.date(2020, 7, 10), datetime.date(2020, 7, 11),
       datetime.date(2020, 7, 12), datetime.date(2020, 7, 13),
       datetime.date(2020, 7, 14), datetime.date(2020, 7, 15),
       datetime.date(2020, 7, 16), datetime.date(2020, 7, 17),
       datetime.date(2020, 6, 1), datetime.date(2020, 6, 2),
       datetime.date(2020, 6, 3), datetime.date(2020, 6, 4),
       datetime.date(2020, 6, 5), datetime.date(2020, 6, 6),
       datetime.date(2020, 1, 1), datetime.date(2020, 1, 2),
       datetime.date(2020, 1, 3), datetime.date(2020, 1, 4),
       datetime.date(2020, 1, 5), datetime.date(2020, 1, 6),
       datetime.date(2020, 1, 7), datetime.date(2020, 1, 8),
       datetime.date(2020, 1, 9), datetime.date(2020, 1, 10),
       datetime.date(2020, 1, 11), datetime.date(2020, 1, 12),
       datetime.date(2020, 1, 13), datetime.date(2020, 1, 14),
       datetime.date(2020, 1, 15), datetime.date(2020, 1, 16),
       datetime.date(2020, 1, 17), datetime.date(2020, 1, 18),
       datetime.date(2020, 1, 19), datetime.date(2020, 1, 20),
       datetime.date(2020, 1, 21), datetime.date(2020, 1, 22),
       datetime.date(2020, 1, 23), datetime.date(2020, 1, 24),
       datetime.date(2020, 1, 25), datetime.date(2020, 1, 26),
       datetime.date(2020, 1, 27), datetime.date(2020, 1, 28),
       datetime.date(2020, 1, 29), datetime.date(2020, 1, 30),
       datetime.date(2020, 1, 31), datetime.date(2020, 2, 1),
       datetime.date(2020, 2, 2), datetime.date(2020, 2, 3),
       datetime.date(2020, 2, 4), datetime.date(2020, 2, 5),
       datetime.date(2020, 2, 6), datetime.date(2020, 2, 7),
       datetime.date(2020, 2, 8), datetime.date(2020, 2, 9),
       datetime.date(2020, 2, 10), datetime.date(2020, 2, 11),
       datetime.date(2020, 2, 12), datetime.date(2020, 2, 13),
       datetime.date(2020, 2, 14), datetime.date(2020, 2, 15),
       datetime.date(2020, 2, 16), datetime.date(2020, 2, 17),
       datetime.date(2020, 2, 18), datetime.date(2020, 2, 19),
       datetime.date(2020, 2, 20), datetime.date(2020, 2, 21),
       datetime.date(2020, 2, 22), datetime.date(2020, 2, 23),
       datetime.date(2020, 2, 24), datetime.date(2020, 2, 25),
       datetime.date(2020, 2, 26), datetime.date(2020, 2, 27),
       datetime.date(2020, 2, 28), datetime.date(2020, 2, 29),
       datetime.date(2020, 3, 1), datetime.date(2020, 3, 2),
       datetime.date(2020, 3, 3), datetime.date(2020, 3, 4),
       datetime.date(2020, 7, 27), datetime.date(2020, 7, 28),
       datetime.date(2020, 7, 29), datetime.date(2020, 7, 30),
       datetime.date(2020, 7, 31), datetime.date(2020, 8, 1),
       datetime.date(2020, 8, 2), datetime.date(2020, 8, 3),
       datetime.date(2020, 8, 4), datetime.date(2020, 8, 5),
       datetime.date(2020, 8, 6), datetime.date(2020, 8, 7),
       datetime.date(2020, 8, 8), datetime.date(2020, 8, 9),
       datetime.date(2020, 8, 10), datetime.date(2020, 8, 11),
       datetime.date(2020, 8, 12), datetime.date(2020, 8, 13),
       datetime.date(2020, 8, 14), datetime.date(2020, 8, 15),
       datetime.date(2020, 8, 17), datetime.date(2020, 8, 18),
       datetime.date(2020, 8, 19), datetime.date(2020, 8, 20),
       datetime.date(2020, 8, 21), datetime.date(2020, 8, 22),
       datetime.date(2020, 8, 23), datetime.date(2020, 8, 24),
       datetime.date(2020, 8, 25), datetime.date(2020, 8, 26),
       datetime.date(2020, 8, 27), datetime.date(2020, 8, 28),
       datetime.date(2020, 8, 29), datetime.date(2020, 8, 30),
       datetime.date(2020, 8, 31), datetime.date(2020, 9, 1),
       datetime.date(2020, 9, 2), datetime.date(2020, 9, 3),
       datetime.date(2020, 9, 4), datetime.date(2020, 9, 5),
       datetime.date(2020, 9, 6), datetime.date(2020, 9, 7),
       datetime.date(2020, 9, 8), datetime.date(2020, 9, 9),
       datetime.date(2020, 9, 10), datetime.date(2020, 9, 11),
       datetime.date(2020, 9, 12), datetime.date(2020, 9, 13),
       datetime.date(2020, 9, 14), datetime.date(2020, 9, 15),
       datetime.date(2020, 9, 16), datetime.date(2020, 9, 17),
       datetime.date(2020, 9, 18), datetime.date(2020, 9, 19),
       datetime.date(2020, 9, 20), datetime.date(2020, 9, 21),
       datetime.date(2020, 9, 22), datetime.date(2020, 9, 23),
       datetime.date(2020, 9, 24), datetime.date(2020, 9, 25),
       datetime.date(2020, 9, 26), datetime.date(2020, 9, 27),
       datetime.date(2020, 9, 28), datetime.date(2020, 9, 29),
       datetime.date(2020, 9, 30), datetime.date(2020, 10, 1),
       datetime.date(2020, 10, 2), datetime.date(2020, 10, 3),
       datetime.date(2020, 10, 4), datetime.date(2020, 10, 5),
       datetime.date(2020, 10, 6), datetime.date(2020, 10, 7),
       datetime.date(2020, 10, 8), datetime.date(2020, 10, 9),
       datetime.date(2020, 10, 10), datetime.date(2020, 10, 11),
       datetime.date(2020, 10, 12), datetime.date(2020, 10, 13),
       datetime.date(2020, 10, 14), datetime.date(2020, 10, 15),
       datetime.date(2020, 10, 16), datetime.date(2020, 10, 17),
       datetime.date(2020, 10, 18), datetime.date(2020, 10, 19),
       datetime.date(2020, 10, 20), datetime.date(2020, 10, 21),
       datetime.date(2020, 10, 22), datetime.date(2020, 10, 23),
       datetime.date(2020, 10, 24), datetime.date(2020, 10, 25),
       datetime.date(2020, 10, 26), datetime.date(2020, 10, 27),
       datetime.date(2020, 10, 28), datetime.date(2020, 10, 29),
       datetime.date(2020, 10, 30), datetime.date(2020, 10, 31),
       datetime.date(2020, 11, 1), datetime.date(2020, 11, 2),
       datetime.date(2020, 11, 3), datetime.date(2020, 11, 4),
       datetime.date(2020, 11, 5), datetime.date(2020, 11, 6),
       datetime.date(2020, 11, 7), datetime.date(2020, 11, 8),
       datetime.date(2020, 11, 9), datetime.date(2020, 11, 10),
       datetime.date(2020, 11, 11), datetime.date(2020, 11, 12),
       datetime.date(2020, 11, 13), datetime.date(2020, 11, 14),
       datetime.date(2020, 11, 15), datetime.date(2020, 11, 16),
       datetime.date(2020, 11, 17), datetime.date(2020, 11, 18),
       datetime.date(2020, 11, 19), datetime.date(2020, 11, 20),
       datetime.date(2020, 11, 21), datetime.date(2020, 11, 22),
       datetime.date(2020, 11, 23), datetime.date(2020, 11, 24),
       datetime.date(2020, 11, 25), datetime.date(2020, 11, 26),
       datetime.date(2020, 11, 27), datetime.date(2020, 11, 28),
       datetime.date(2020, 11, 29), datetime.date(2020, 11, 30),
       datetime.date(2020, 12, 1), datetime.date(2020, 12, 2),
       datetime.date(2020, 12, 3), datetime.date(2020, 12, 4),
       datetime.date(2020, 12, 5), datetime.date(2020, 12, 6),
       datetime.date(2020, 12, 7), datetime.date(2020, 12, 8),
       datetime.date(2020, 12, 9), datetime.date(2020, 12, 10),
       datetime.date(2020, 12, 11), datetime.date(2020, 12, 12),
       datetime.date(2020, 12, 13), datetime.date(2020, 12, 14),
       datetime.date(2020, 12, 15), datetime.date(2020, 12, 16),
       datetime.date(2020, 12, 17), datetime.date(2020, 12, 18),
       datetime.date(2020, 12, 19), datetime.date(2020, 12, 20),
       datetime.date(2020, 12, 21), datetime.date(2020, 12, 22),
       datetime.date(2020, 12, 23), datetime.date(2020, 12, 24),
       datetime.date(2020, 12, 25), datetime.date(2020, 12, 26),
       datetime.date(2020, 12, 27), datetime.date(2020, 12, 28),
       datetime.date(2020, 12, 29), datetime.date(2020, 12, 30),
       datetime.date(2020, 12, 31), datetime.date(2021, 1, 1),
       datetime.date(2020, 5, 31), datetime.date(2020, 7, 18),
       datetime.date(2020, 7, 19), datetime.date(2020, 7, 20),
       datetime.date(2020, 7, 21), datetime.date(2020, 7, 22),
       datetime.date(2020, 7, 23), datetime.date(2020, 7, 24),
       datetime.date(2020, 7, 25), datetime.date(2020, 7, 26),
       datetime.date(2020, 8, 16)], dtype=object)

Check the lon/lat of each buoy platform

In [ ]:
# group dataset by the platform id and show lat and lon in each platform, while also reset the index of dataset
lat_lon_list = df_altim.groupby('platform_id')[['latitude', 'longitude']].first().reset_index()
lat_lon_list

             platform_id   latitude  longitude
0                  61277  35.726300  25.130700
1                1801573  36.015130  -5.991100
2                5801955  36.005120  -5.983470
3                6100002  42.071800   4.650300
4                6100021  42.930000   6.207000
5                6100022  43.713580   7.426170
6                6100188  42.488300   3.168300
7                6100190  43.371500   3.779700
8                6100191  42.916200   3.124500
9                6100196  41.900000   3.650000
10               6100197  39.710000   4.420000
11               6100198  36.570000  -2.340000
12               6100280  40.690000   1.470000
13               6100281  39.510000   0.200000
14               6100284  43.318900   4.866200
15               6100289  43.208340   5.230000
16               6100294  42.569200   8.650000
17               6100295  42.261700   9.643300
18               6100417  37.650000  -0.310000
19               6100430  39.560000   2.090000
20               6100431  43.425000   4.133300
21               6101404  36.066000  -5.416000
22               6101628  45.603300  13.671700
23               6101629  45.601600  13.535400
24               6100021  42.930000   6.207000
25               6100022  43.713580   7.426170
26               6100290  43.316120   4.920370
27               6100295  42.261700   9.643300
28               6100431  43.425000   4.133300
29               6101404  36.066000  -5.416000
30                 61277  35.726300  25.130700
31                 61499  39.492800   2.700400
32                 68422  36.828800  21.606800
33             ADN-DWRG1  45.565500  13.248000
34             ADN-DWRG2  45.699500  13.209000
35             ADN-DWRG3  45.688300  13.521300
36                 ATHOS  39.975000  24.729400
37  Barcelona-coast-buoy  41.320000   2.200000
38              CAPOMELE  43.921670   8.177000
39      Ceuta-coast-buoy  35.903000  -5.330000
40             HERAKLION  35.434200  25.079200
41               Kariani  40.728916  23.973534
42                 MYKON  37.519400  25.459700
43     Malaga-coast-buoy  36.692000  -4.415000
44    Melilla-coast-buoy  35.327000  -2.944000
45                 OBSEA  41.182120   1.752570
46     Tarifa-coast-buoy  36.000000  -5.590000
47  Tarragona-coast-buoy  41.070000   1.190000

Find the corresponding indecies of each platfrom on model's domain via a kdtree

In [ ]:
# require libraries
import numpy as np
import pandas as pd
from scipy.spatial import cKDTree

# -------------------------------------------
# 1. PREPARE MODEL GRID & KDTREE (done once)
# -------------------------------------------
lat2d = ds_0["latitude"].values
lon2d = ds_0["longitude"].values

ny, nx = lat2d.shape
lat_flat = lat2d.ravel()
lon_flat = lon2d.ravel()

coords_model = np.column_stack([
    np.radians(lat_flat),
    np.radians(lon_flat)
])
tree = cKDTree(coords_model)

# -------------------------------------------
# 2. LOOP OVER PLATFORMS
# -------------------------------------------
results = []

for platform, df_plat in df_altim.groupby("platform_id"):

    lat_obs = df_plat["latitude"].values
    lon_obs = df_plat["longitude"].values

    coords_obs = np.column_stack([
        np.radians(lat_obs),
        np.radians(lon_obs)
    ])
    
    # Spatial match
    dist, idx_flat = tree.query(coords_obs)
    j_idx, i_idx = np.unravel_index(idx_flat, (ny, nx))

    # Build DataFrame for this platform
    df_out = pd.DataFrame({
        "platform": platform,
        "latitude": lat_obs,
        "longitude": lon_obs,
        "j_idx": j_idx,
        "i_idx": i_idx
    })

    results.append(df_out)

# -------------------------------------------
# 3. CONCAT RESULTS FOR ALL PLATFORMS
# -------------------------------------------
df_kdtree_output = pd.concat(results, ignore_index=True)
df_kdtree_output

                    platform  latitude  longitude  j_idx  i_idx
0                      61277   35.7263    25.1307    259   1249
1                      61277   35.7263    25.1307    259   1249
2                      61277   35.7263    25.1307    259   1249
3                      61277   35.7263    25.1307    259   1249
4                      61277   35.7263    25.1307    259   1249
...                      ...       ...        ...    ...    ...
546185  Tarragona-coast-buoy   41.0700     1.1900    493    381
546186  Tarragona-coast-buoy   41.0700     1.1900    493    381
546187  Tarragona-coast-buoy   41.0700     1.1900    493    381
546188  Tarragona-coast-buoy   41.0700     1.1900    493    381
546189  Tarragona-coast-buoy   41.0700     1.1900    493    381

[546190 rows x 5 columns]

In [14]:
index_list = df_kdtree_output.groupby('platform')[['latitude', 'longitude', 
                                                   'j_idx', 'i_idx']].first().reset_index()
index_list

                platform   latitude  longitude  j_idx  i_idx
0                  61277  35.726300  25.130700    259   1249
1                1801573  36.015130  -5.991100    248    130
2                5801955  36.005120  -5.983470    248    130
3                6100002  42.071800   4.650300    549    502
4                6100021  42.930000   6.207000    597    555
5                6100022  43.713580   7.426170    641    596
6                6100188  42.488300   3.168300    567    449
7                6100190  43.371500   3.779700    614    468
8                6100191  42.916200   3.124500    589    446
9                6100196  41.900000   3.650000    538    467
10               6100197  39.710000   4.420000    430    499
11               6100198  36.570000  -2.340000    275    261
12               6100280  40.690000   1.470000    474    392
13               6100281  39.510000   0.200000    415    348
14               6100284  43.318900   4.866200    614    507
15               6100289  43.208340   5.230000    609    520
16               6100294  42.569200   8.650000    584    644
17               6100295  42.261700   9.643300    570    680
18               6100417  37.650000  -0.310000    327    332
19               6100430  39.560000   2.090000    420    416
20               6100431  43.425000   4.133300    618    480
21               6101404  36.066000  -5.416000    251    151
22               6101628  45.603300  13.671700    767    810
23               6101629  45.601600  13.535400    767    805
24               6100021  42.930000   6.207000    597    555
25               6100022  43.713580   7.426170    641    596
26               6100290  43.316120   4.920370    614    509
27               6100295  42.261700   9.643300    570    680
28               6100431  43.425000   4.133300    618    480
29               6101404  36.066000  -5.416000    251    151
30                 61277  35.726300  25.130700    259   1249
31                 61499  39.492800   2.700400    417    438
32                 68422  36.828800  21.606800    310   1121
33             ADN-DWRG1  45.565500  13.248000    763    795
34             ADN-DWRG2  45.699500  13.209000    771    793
35             ADN-DWRG3  45.688300  13.521300    772    804
36                 ATHOS  39.975000  24.729400    483   1227
37  Barcelona-coast-buoy  41.320000   2.200000    507    417
38              CAPOMELE  43.921670   8.177000    654    622
39      Ceuta-coast-buoy  35.903000  -5.330000    243    154
40             HERAKLION  35.434200  25.079200    245   1247
41               Kariani  40.728916  23.973534    523   1198
42                 MYKON  37.519400  25.459700    351   1258
43     Malaga-coast-buoy  36.692000  -4.415000    280    186
44    Melilla-coast-buoy  35.327000  -2.944000    219    240
45                 OBSEA  41.182120   1.752570    499    401
46     Tarifa-coast-buoy  36.000000  -5.590000    248    144
47  Tarragona-coast-buoy  41.070000   1.190000    493    381